name: Tests
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    # Set up Flutter.
    - name: Clone Flutter repository with 'beta' channel
      uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter doctor -v

    # Checkout gallery code and get packages.
    - name: Checkout gallery code
      uses: actions/checkout@v2
    - run: flutter pub get

    # Analyze, check formatting, and run unit tests.
    - run: flutter analyze
    # Can't be bothered honestly...
    #- name: Ensure the Dart code is formatted correctly
    #  run: flutter format --set-exit-if-changed --dry-run .
    - name: Run Flutter unit tests
      run: flutter test
